// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8Z_crqwSg4vegNzEn76fZQohzw7kgp6w',
    appId: '1:667032728557:web:620df6ac67b0c2dde6ede4',
    messagingSenderId: '667032728557',
    projectId: 'gaflutter-41bd1',
    authDomain: 'gaflutter-41bd1.firebaseapp.com',
    databaseURL: 'https://gaflutter-41bd1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gaflutter-41bd1.firebasestorage.app',
    measurementId: 'G-EFDMEXCLK4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAum2JkJPMFjYTquxFJh2ygoL5WFGptiBI',
    appId: '1:667032728557:android:d18006a510848ea5e6ede4',
    messagingSenderId: '667032728557',
    projectId: 'gaflutter-41bd1',
    databaseURL: 'https://gaflutter-41bd1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gaflutter-41bd1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXnJ1Y3b0AIQm8KMZxBmbTSDLeB4Eq5xg',
    appId: '1:667032728557:ios:da6414c6275380ede6ede4',
    messagingSenderId: '667032728557',
    projectId: 'gaflutter-41bd1',
    databaseURL: 'https://gaflutter-41bd1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gaflutter-41bd1.firebasestorage.app',
    iosClientId: '667032728557-u065ts6b4523jg411rphl8ucsf7vjfdd.apps.googleusercontent.com',
    iosBundleId: 'com.example.gaflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXnJ1Y3b0AIQm8KMZxBmbTSDLeB4Eq5xg',
    appId: '1:667032728557:ios:da6414c6275380ede6ede4',
    messagingSenderId: '667032728557',
    projectId: 'gaflutter-41bd1',
    databaseURL: 'https://gaflutter-41bd1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gaflutter-41bd1.firebasestorage.app',
    iosClientId: '667032728557-u065ts6b4523jg411rphl8ucsf7vjfdd.apps.googleusercontent.com',
    iosBundleId: 'com.example.gaflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8Z_crqwSg4vegNzEn76fZQohzw7kgp6w',
    appId: '1:667032728557:web:cf8589f55954a788e6ede4',
    messagingSenderId: '667032728557',
    projectId: 'gaflutter-41bd1',
    authDomain: 'gaflutter-41bd1.firebaseapp.com',
    databaseURL: 'https://gaflutter-41bd1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gaflutter-41bd1.firebasestorage.app',
    measurementId: 'G-ZJLWYZTSYC',
  );

}